## This makeCacheMatrix function try to save your matrix into cache first.
## For example, you created your matrix and save it to `myMatrix` variable:
##
## myMatrix <- matrix(c(1,2,2,1), nrow=2, byrow=TRUE)
##
## Now, `myMatrix` variable saved your matrix
## The makeCacheMatrix save your matrix into cache by passing your matrix.
## Lets create a new variable called `matrixCache` and pass the output of
## your function as a list
##
## matrixCache <- makeCacheMatrix(myMatrix)
##
## The function will then save your matrix with a null inverse since we haven't
## solve its inverse yet. 
## Inside our function, we have set, get, setinv, and getinv function
##
## `set` function sets a new matrix to your old makeCacheMatrix variable. Since
## we have `matrixCache` variable that has our cached matrix, we can replace
## that matrix with new matrix, e.g.
##
## matrixCache.set(matrix(c(4,13,11,12), nrow=2, byrow=TRUE))
##
## This expression will then replace our old matrix with our passed matrix. 
## Notice that we reset our inv to NULL since we haven't solve the inverse of
## our new matrix yet.
##
## `get` function get the cached matrix in our old makeCacheMatrix variable.
##
## matrixCache.get()
##       [,1] [,2]
## [1,]     4  13
## [2,]    11  12
##
## This will output our cached matrix
##
## `setinv` will take the solved inverse as its argument and save the inv in
## our cache with respect to our matrix.
##
## matrixCache.setinv(solve(matrixCache.get()))
##
## `getinv` will get the inverse of our matrix in `makeCacheMatrix` variable.
##
## matrixCache.getinv()
##       [,1]      [,2]
## [1,]  -0.1263   0.1368
## [2,]   0.1158  -0.0421
##
## But notice, we are going to repeat these steps if we are going to create 
## another matrix and its inverse in our cache. The solution is we create 
## another function that will only take the `matrixCache`
##
## `cacheSolve` function will check if the matrix has already its inverse in
## the cache. If the matrix inverse is not NULL, it will then output the
## message to the console to notify that the inverse was fetched from the cache
## Then the function will return the inverse of the matrix. If the inverse of
## our matrix is NULL, the `solve` function of R to generate the inverse of our 
## matrix. The generated inverse will be saved into cached by calling the
## `setinv` function of matrixCache and the inverse will be returned to the user
## without any message, notifying that the solved inverse was generated by
## `solve` and not fetch from cache.
##
## Example:
##
## If you call the `cacheSolve` function to our `matrixCache`, it will solved its
## inverse since it is the first time calling the `solve` function.
##
## cacheSolve(matrixCache)
##       [,1]      [,2]
## [1,]  -0.1263   0.1368
## [2,]   0.1158  -0.0421
##
## If you call the `cacheSolve` function again to solve the `matrixCache`, the
## function will generate a message and output the inverse from cache
##
## cacheSolve(matrixCache)
## getting cached data
##       [,1]      [,2]
## [1,]  -0.1263   0.1368
## [2,]   0.1158  -0.0421
##
## And that's it!


## Save the matrix into cache.

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y){
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  setinv <- function(inverse) inv <<- inverse
  getinv <- function() inv
  list(set = set, 
       get = get, 
       setinv = setinv, 
       getinv = getinv)
}


## Solves the inverse of the matrix stored in the makeCacheMatrix and save it
## to cache. If the inverse is already in the cache, it will fetch that inverse.

cacheSolve <- function(x, ...) {
  inv <- x$getinv()
  if(!is.null(inv)){
    message("getting cached data")
    return(inv)
  }
  data <- x$get()
  inv <- solve(data)
  x$setinv(inv)
  inv
}
